# Generated by Django 3.2.8 on 2021-10-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.AddField(
            model_name='record',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
